name: Deploy to Docker Hub

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy HTML to Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vaibhavborate/html-app:latest

